### ISSUE TITLE
WebAlign removes nonlinear markers on save

### ISSUE THREAD

**Issue by PolarBean** [Neural-Systems-at-UIO/WebAlign#31]
I like to go back and forth between webalign and webwarp in the workbench. but it appears that when i do it deletes my nonlinear markers. Would it be possible for it to only update the ouv and not the markers? 

thank you in advance

**Comment by Tevemadar** [comment]
This is intentional, markers lose their meaning when base alignment changes. However deletion of markers is restricted, it happens to the section itself and the surrounding propagation block (so in both directions up to the next section which has its own alignement).
There's a known issue though: "undo" doesn't restore deleted markers.

**Comment by PolarBean** [comment]
I understand that perspective, at the same time when I have spent 10 minutes creating the perfect deformation, and then decide to adjust the angle by 1 degree, I don't want to lose my markers. 

You could have a popup when the users comes back to say "this files alignments have changed since you last set the markers, should we clear the markers of the adjusted sections?"

**Comment by Tevemadar** [comment]
Feature disabled in https://github.com/Neural-Systems-at-UIO/WebAlign/commit/4ed0bf81d13291b37de8db83410710c9068dc016
